hw
mate-academy/hibernate-criteria-query pull request #75
Opened 2021-01-30 09:49 UTC by vlykhvar

2021-01-30 17:42 UTC, gigbat approved these changes

2021-02-01 09:41 UTC, KseniiaMakarova requested changes

2021-02-01 09:41 UTC, KseniiaMakarova commented on src/main/java/ma/hibernate/dao/PhoneDaoImpl.java
> +                predicates.add(root.get(entry.getKey()).in((Object[]) entry.getValue()));
```suggestion
                predicates.add(root.get(entry.getKey()).in(entry.getValue()));
```
do we need this cast?

2021-02-01 09:41 UTC, KseniiaMakarova commented on src/main/java/ma/hibernate/dao/PhoneDaoImpl.java
> +            throw new RuntimeException("Have not got all cellphone ", e);
```suggestion
            throw new RuntimeException("Can't get list of phones ", e);
```

2021-02-01 10:37 UTC, KseniiaMakarova requested changes
the code is ok, but please tell what is wrong here and what should we do?
![image](https://user-images.githubusercontent.com/59459757/106447531-46249880-648a-11eb-85ed-e25d5970fe44.png)

2021-02-01 11:42 UTC, closed without merging